
export const tasks = [
  {
    title: "Develop Smart Contract for NFT Marketplace",
    description:
      "Seeking an experienced Solidity developer to create a secure and efficient smart contract for our upcoming NFT marketplace.",
    status: "Verifying",
    creator: "AliceCryptoDev",
    reward: 0.5,
    currency: "ETH",
    usdEquivalent: 1500,
    tags: ["Solidity", "ERC-721", "NFT", "Marketplace"],
    rating: 4.2,
    dueDate: "2024-04-15",
    createdAt: "2024-03-01",
  },
  {
    title: "Design UI/UX for dApp Dashboard",
    description:
      "We need a skilled UI/UX designer to create an intuitive and visually appealing dashboard for our decentralized application focused on DeFi.",
    status: "Progress",
    creator: "DesignQueen",
    reward: 0.2,
    currency: "ETH",
    usdEquivalent: 600,
    tags: ["UI/UX", "Figma", "DeFi", "Dashboard"],
    rating: 4.7,
    dueDate: "2024-03-30",
    createdAt: "2024-02-25",
  },
  {
    title: "Community Moderation for Discord Server",
    description:
      "Looking for a reliable and experienced community moderator to manage our project's active Discord server (20k+ members).",
    status: "Completed",
    creator: "CryptoComms",
    reward: 500,
    currency: "USDC",
    usdEquivalent: 500,
    tags: ["Community", "Discord", "Moderation", "Support"],
    rating: 5.0,
    dueDate: "2024-03-10",
    createdAt: "2024-02-20",
  },
  {
    title: "Build Token Gating Smart Contract",
    description:
      "Need a Solidity developer to create a smart contract that gates access to specific content based on token holdings.",
    status: "Open",
    creator: "TokenWizard",
    reward: 0.3,
    currency: "ETH",
    usdEquivalent: 900,
    tags: ["Solidity", "AccessControl", "ERC-20"],
    rating: 4.5,
    dueDate: "2024-04-20",
    createdAt: "2024-03-05",
  },
  {
    title: "Landing Page Design for Web3 Startup",
    description:
      "Looking for a creative designer to design a sleek landing page using Figma and Tailwind for our new Web3 product.",
    status: "Open",
    creator: "Web3Pixel",
    reward: 300,
    currency: "USDC",
    usdEquivalent: 300,
    tags: ["UI/UX", "Tailwind", "Figma"],
    rating: 4.8,
    dueDate: "2024-04-10",
    createdAt: "2024-03-03",
  },
  {
    title: "Deploy Frontend on IPFS",
    description:
      "Need assistance deploying our React.js frontend onto IPFS with proper metadata handling and pinning.",
    status: "Progress",
    creator: "PinMaster",
    reward: 0.1,
    currency: "ETH",
    usdEquivalent: 300,
    tags: ["IPFS", "React", "Frontend"],
    rating: 4.3,
    dueDate: "2024-03-28",
    createdAt: "2024-02-22",
  },
  {
    title: "Smart Contract Audit",
    description:
      "Seeking a security expert to audit a smart contract with multiple methods including minting, transferring, and burning.",
    status: "Open",
    creator: "AuditGuru",
    reward: 0.4,
    currency: "ETH",
    usdEquivalent: 1200,
    tags: ["Audit", "Security", "Solidity"],
    rating: 4.9,
    dueDate: "2024-04-05",
    createdAt: "2024-02-28",
  },
  {
    title: "Create Onboarding Flow for Wallet Connection",
    description:
      "Design and develop an onboarding modal to help users easily connect wallets using RainbowKit.",
    status: "Completed",
    creator: "OnboardX",
    reward: 0.15,
    currency: "ETH",
    usdEquivalent: 450,
    tags: ["Onboarding", "Wallet", "RainbowKit"],
    rating: 4.6,
    dueDate: "2024-03-15",
    createdAt: "2024-02-20",
  },
  {
    title: "Set Up MongoDB Schema for NFT Metadata",
    description:
      "We need a developer to structure and implement a MongoDB schema to handle NFT data fetched via Viem.",
    status: "Open",
    creator: "DataChainDev",
    reward: 0.25,
    currency: "ETH",
    usdEquivalent: 750,
    tags: ["MongoDB", "Schema", "NFT", "Viem"],
    rating: 4.4,
    dueDate: "2024-04-18",
    createdAt: "2024-03-04",
  },
  {
    title: "Create Email Notification Service for New Bids",
    description:
      "Set up a notification system using Node.js and SendGrid to alert users when a new bid is placed on their NFT listing.",
    status: "Progress",
    creator: "NotifyMe",
    reward: 0.2,
    currency: "ETH",
    usdEquivalent: 600,
    tags: ["Node.js", "SendGrid", "Notifications"],
    rating: 4.1,
    dueDate: "2024-03-27",
    createdAt: "2024-02-24",
  },
];

